import localFont from 'next/font/local';
import './globals.css';
import Header from './Components/Header';
import { UserContextProvider } from './Context/UserContext';
import { TimerProvider } from './Context/TimerContext';

import { DM_Sans } from 'next/font/google';
import GoogleSignIn from './Components/GoogleSignIn';

const dmSans = DM_Sans({
  subsets: ['latin'], // Load only necessary character sets
  weight: ['400', '500', '700'], // Choose the font weights you need
  variable: '--font-dm-sans', // Optional: for using in Tailwind
});

export const metadata = {
  title: 'Amarex Express',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  GoogleSignIn();
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} antialiased bg-primary-950  min-h-screen flex flex-col relative text-zinc-900 font-medium`}
      >
        <TimerProvider>
          <UserContextProvider>
            <Header />
            <div>
              <main>{children}</main>
            </div>
          </UserContextProvider>
        </TimerProvider>
      </body>
    </html>
  );
}
